# 예외 처리
## 프로그램 오류
- 프로그램 실행 중 비정상적인 종료 또는 오작동하게되는 원인.

## 오류의 종류
1. 컴파일 오류(compile error)
- 컴파일 시점에 발생하는 오류.
- 오류 발생 시 컴파일이 되지 않아 프로그램 실행이 불가능하다.

2. 실행 오류(runtime error)
- 실행 시점에 발생하는 오류
- 실행 오류 중 프로그램을 잘못 수행하여 의도하지 않은 결과가 실행되어 생기게 되는 것을 ***버그(bug)***라고 한다.

## 오류와 예외
- 실행 오류에는 크게 두가지로 구분된다.
    1. 시스템 오류(error)
        - 자바 가상 머신에서 발생하는 오류
        - 사용가능한 동적 메모리가 없는 경우 또는 스택 메모리의 오버 플로우가 발생한 경우 등이 있다.
        - 이러한 오류는 개발자가 프로그램 코딩으로 제어가 불가능하다.

    2. 예외(exception)
        - 프로그램 코딩으로 제어가 가능한 오류.

## 예외 클래스 종류

![Alt text](https://raw.githubusercontent.com/yonggyo1125/curriculum300H/main/1.JAVA%2884%EC%8B%9C%EA%B0%84%29/11%EC%9D%BC%EC%B0%A8%283h%29%20-%20%EC%98%88%EC%99%B8%EC%B2%98%EB%A6%AC%2C%20java.lang%ED%8C%A8%ED%82%A4%EC%A7%80%2C%20%EC%9C%A0%EC%9A%A9%ED%95%9C%ED%81%B4%EB%9E%98%EC%8A%A4/images/%EC%98%88%EC%99%B8%EC%B2%98%EB%A6%AC1.png)

- 위 그림은 프로그램 오류 관련 자바 내 클래스의 상속관계를 의미한다.
- 이 중 프로그램 코딩으로 처리가 가능한 예외의 최상위 클래스는 Exception 클래스이다.

![Alt text](https://raw.githubusercontent.com/yonggyo1125/curriculum300H/main/1.JAVA%2884%EC%8B%9C%EA%B0%84%29/11%EC%9D%BC%EC%B0%A8%283h%29%20-%20%EC%98%88%EC%99%B8%EC%B2%98%EB%A6%AC%2C%20java.lang%ED%8C%A8%ED%82%A4%EC%A7%80%2C%20%EC%9C%A0%EC%9A%A9%ED%95%9C%ED%81%B4%EB%9E%98%EC%8A%A4/images/%EC%98%88%EC%99%B8%EC%B2%98%EB%A6%AC2.png)
- 위 그림은 Exception 하위 클래스 중 사용 빈도가 높은 클래스 위주로 계층도를 표현한 그림이다.
- 가장 크게 구분되는 종류는 ***RuntimeException*** 클래스와 ***Exception*** 클래스로 나눌 수있다.
    - Exception 클래스는 RuntimeException 클래스가 아닌 클래스들이다.
- 구분 기준은 컴파일 오류 발생 유무인데, RuntimeException 클래스들은 예외 처리를 하지 않아도 컴파일러에서 관여하지 않아 컴파일 오류가 발생하지 않는다.
- 하지만, Exception 클래스들은 예외 발생 시 컴파일이 불가하게 되어 프로그램 실행이 아예되지 않게 된다.
- 컴파일러에 의해 확인되지 않는 예외는 프로그래머가 알아서 처리해야 하므로 주의가 필요하다.

## 예외 처리하기
### try ~ catch 구문

```
try {
	예외가 발생할 수 있는 코드 부분
} catch (처리할 예외 클래스 타입 e) {
	try 블록 안에서 예외가 발생했을 때 예외를 처리하는 부분
}
```

- try 블록에는 예외가 발생할 가능성이 있는 코드를 작성.
- try 블록 안에 예외 발생 시 catch 블록 안 구문이 수행된다.
- catch 구문의 () 안에 예외 클래스 타입은 상황에 따라 달라진다.
- 예외 처리는 프로그램이 비정상적으로 종료되는 것을 방지할 수 있으므로 매우 중요하다.

### 예외 처리 흐름
1. 예외 발생
- try 블록 -> 예외 발생 -> try 블록 탈출 & catch 블록 구문 실행
-> 예외 처리 -> try ~ catch 구문 탈출 -> 남은 실행구문 실행 -> 종료

2. 예외 발생하지 않음.
- try 블록 -> 예외 발생 X -> try ~ catch 구문 탈출 -> 남은 실행구문 실행 -> 종료

### try ~ catch ~ finally 구문
- finally 블록 구문은 예외 발생과 상관없이 반드시 실행되는 구문.
- try나 catch 구문 내 return 예약자가 있어도 실행되는 구문이다.
    - 원래 return 예약어가 있는 경우, 실행중인 함수 종료를 의미한다.
```
try {
	예외가 발생할 수 있는 부분
} catch (처리할 예외 타입 e) {
	예외를 처리하는 부분
} finally {
	항상 수행되는 부분
}
```

```
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;

public class ExceptionHandling2 {
	public static void main(String[] args) {
		FileInputStream fis = null;
		
		try {
			fis = new FileInputStream("a.txt");
		} catch (FileNotFoundException e) {
			System.out.println(e);
			return;
		} finally {
			if (fis != null) {
				try {
					fis.close();  // 파일 입력 스트림 닫기
				} catch (IOException e) {
					e.printStackTrace();
				}
			}
			System.out.println("항상 수행됩니다.");
		}
		System.out.println("여기도 수행됩니다.");
	}
}

실행결과

java.io.FileNotFoundException: a.txt (지정된 파일을 찾을 수 없습니다)
항상 수행됩니다.
``` 

- 프로그램에서 사용한 리소스는 프로그램이 종료되면 자동으로 해제된다.
- 예를 들어 네트워크가 연결되었을 경우에 채팅 프로그램이 종료될 때 연결도 닫히게 된다.
- 하지만 끝나지 않고 계속 수행되는 서비스 같은 경우 리소스를 여러번 반복해서 열기만 하고 닫지 않게되면 문제가 발생하게 된다. 시스템에서 허용하는 자원은 한계가 있기 때문이다.
- 사용한 시스템 리소스는 반드시 사용 후 close() 메서드로 닫아줘야 한다.
- 파일 접근을 위해 열린 리소스는 예외 발생과 상관없이 항상 닫혀야 하므로 finally 블록에 파일 리소스를 다든 코드를 구현한다.

### try ~ with ~ resources 구문
- 시스템 리소스를 사용하고 해제하는 코드는 다소 복잡하다.
- JDK 1.7 버전 이후 부터 try~with~resource 구문을 제공하여 close() 메서드를 명시적으로 호출하지 않아도 try 블록 내에서 열린 리소스를 자동으로 닫도록 만들 수 있다.
- 단, try~with~resource 구문을 사용하려면 해당 리소스가 AutoCloseable 인터페이스를 구현해야 한다.
- AutoCloseable 인터페이스에는 close() 메서드가 있고 이를 구현한 클래스는 close()를 명시적으로 호출하지 않아도 메서드가 호출된다.

>FileInputStream 예시
![Alt text](https://raw.githubusercontent.com/yonggyo1125/curriculum300H/main/1.JAVA%2884%EC%8B%9C%EA%B0%84%29/11%EC%9D%BC%EC%B0%A8%283h%29%20-%20%EC%98%88%EC%99%B8%EC%B2%98%EB%A6%AC%2C%20java.lang%ED%8C%A8%ED%82%A4%EC%A7%80%2C%20%EC%9C%A0%EC%9A%A9%ED%95%9C%ED%81%B4%EB%9E%98%EC%8A%A4/images/%EC%98%88%EC%99%B8%EC%B2%98%EB%A6%AC3.png)

```

public class AutoCloseObj implements AutoCloseable {
	@Override
	public void close() throws Exception {
		System.out.println("리소스가 close() 되었습니다.");
	}
}

public class AutoCloseTest {
	public static void main(String[] args) {
		try (AutoCloseObj obj = new AutoCloseObj()) { // 사용할 리소스 선언
			
		} catch(Exception e) {
			System.out.println("예외 부분 입니다.");
		}
	}
}

실행결과

리소스가 close() 되었습니다.

```
- AutoCloseable 인터페이스는 반드시 close() 메서드를 구현해야 한다.
- try-with-resource 구문 사용 시 try 구문 괄호() 안에 리소스를 선언해야 한다.
- () 안에 리소스 객체를 다수 생성 시 세미 콜론(;)으로 구분해준다.

```
try(A a = new A(); B b = new B()) {
	...
} catch(Exception e) {
	...
}
```

```
package day11.exception;

public class AutoCloseObjTest {
	public static void main(String[] args) {
		try (AutoCloseObj obj = new AutoCloseObj()) { // 사용할 리소스 선언
			throw new Exception(); // 강제 예외 발생
		} catch(Exception e) {
			System.out.println("예외 부분 입니다.");
		}
	}
}


실행결과

리소스가 close() 되었습니다.
예외 부분 입니다.
```
- `throw + new 생성자식`을 사용하면 예외 객체를 강제 생성할 수 있다.
- 실행 결과를 보면 close() 메서드가 먼저 호출되고 예외 블록이 수행되는 것을 알 수 있다.
- 이처럼 try-with-resource 구문을 사용하면 close() 메서드를 명시적으로 호출하지 않아도 정상 종료된 경우와 예외가 발생한 경우 모두 리소스를 해제 해준다.

### multi catch 구문
```
 public static void main(String[] args) {
 	ThrowsException test = new ThrowsException();
 	try {
 		test.loadClass("a.txt", "java.lang.String");
 	} catch (FileNotFoundException | ClassNotFoundException e) {
 		// TODO Auto-generated catch block
 		e.printStackTrace();
 	} 
 }
```
- 여러 예외를 처리할 경우 catch 구문을 여러개 나열해야 하지만 하나의 catch() {} 구문으로 여러 예외를 한번에 처리시 multi catch 구문을 사용한다.
- catch () 괄호 안에 예외 클래스 타입을 적어준 뒤 ***|*** 기호로 구분하여 함께 선언해준다.
- 주의할 점은 선언된 예외 클래스는 서로 상속관계이면 안된다. 즉, 한쪽이 부모이고 한쪽이 자식이면 안된다.

### 다중 예외 처리
- 어떤 예외가 발생할지 미리 알수는 없지만 모든 예외 상황을 처리하고자 한다면 맨 마지막 부분에 Exception 클래스를 활용하여 catch 블록을 추가한다.
- Exception 클래스는 모든 예외 클래스의 최상위 클래스 이므로 다른 catch 블록에서 선언한 것 이외의 예외가 발생하더라도 Exception 클래스로 자동 형변환(다형성)된다.
- 가장 처음 Exception이 catch 구간에 있을 경우 모든 예외가 이 구간으로 유입되어 적절한 예외처리가 불가능하므로 기본 예외 처리를 하는 Exception 클래스 블록은 여러 예외처리 블록의 가장 아래에 위치하는 것이 일반적이다.

## 예외 처리 미루기
### throws 예약어 사용
- 예외가 발생한 A 메서드에서 throws 예약어 사용 시 메서드에서 예외를 처리하지 않고 A 메서드를 호출하여 사용하는 부분에서 예외를 처리하도록 전가한다.

```
package day11.exception;

import java.io.FileInputStream;
import java.io.FileNotFoundException;

public class ThrowsException {
	public Class loadClass(String fileName, String className) throws FileNotFoundException, ClassNotFoundException {
		FileInputStream fis = new FileInputStream(fileName); // FileNotFoundException 발생 가능
		Class c = Class.forName(className); // ClassNotFoundException 발생 가능
		return c;
	}
	public static void main(String[] args) {
		ThrowsException test = new ThrowsException();
		test.loadClass("a.txt", "java.lang.String"); // 메서드 호출할 때 예외처리함
	}
}
```

- 예외를 처리하지 않고 미루게 되면 그 메서드를 호출하여 사용하는 부분에서 예외처리를 해야한다.

![Alt text](https://raw.githubusercontent.com/yonggyo1125/curriculum300H/main/1.JAVA%2884%EC%8B%9C%EA%B0%84%29/11%EC%9D%BC%EC%B0%A8%283h%29%20-%20%EC%98%88%EC%99%B8%EC%B2%98%EB%A6%AC%2C%20java.lang%ED%8C%A8%ED%82%A4%EC%A7%80%2C%20%EC%9C%A0%EC%9A%A9%ED%95%9C%ED%81%B4%EB%9E%98%EC%8A%A4/images/%EC%98%88%EC%99%B8%EC%B2%98%EB%A6%AC4.png)

![Alt text](https://raw.githubusercontent.com/yonggyo1125/curriculum300H/main/1.JAVA%2884%EC%8B%9C%EA%B0%84%29/11%EC%9D%BC%EC%B0%A8%283h%29%20-%20%EC%98%88%EC%99%B8%EC%B2%98%EB%A6%AC%2C%20java.lang%ED%8C%A8%ED%82%A4%EC%A7%80%2C%20%EC%9C%A0%EC%9A%A9%ED%95%9C%ED%81%B4%EB%9E%98%EC%8A%A4/images/%EC%98%88%EC%99%B8%EC%B2%98%EB%A6%AC5.png)

- main() 함수 선언 부분에 throws를 추가할 경우 예외 처리를 미루게 되는데, 이는 자바 가상 머신으로 보내지게 된다.
- 즉, 예외를 처리하는 것이 아니라 프로그램이 비정상 종료된다.

## 사용자 정의 예외
- 사용자 정의 예외 클래스를 구현 시 기존 JDK에서 제공하는 예외 클래스 중 가장 유사한 클래스를 상속받는 것이 좋다.
- 유사한 예외 클래스를 잘 모를 경우 가장 상위 클래스인 Exception 클래스를 상속받으면 된다.(가장 일반적이다.)

```
public class IDFormatException extends Exception {
	// 생성자의 매개변수로 예외 상황 메시지를 받음
	public IDFormatException(String message) {
		super(message);
	}
}

public class IDFormatTest {
	private String userID;
	
	public String getUserID() {
		return userID;
	}
	
	public void setUserID(String userID) throws IDFormatException {
		if (userID == null) {
			// 강제로 예외 발생
			throw new IDFormatException("아이디는 null일 수 없습니다.");
		} else if (userID.length() > 0 || userID.length() > 20) {
			// 강제로 예외 발생 
			throw new IDFormatException("아이디는 8자 이상 20자 이하로 쓰세요");
		}
		this.userID = userID;
	}
	
	public static void main(String[] args) {
		IDFormatTest test = new IDFormatTest();
		
		String userID = null; // 아이디 값이 null인 경우
		try {
			test.setUserID(userID); 
		} catch (IDFormatException e) {
			System.out.println(e.getMessage());
		}
		
		userID = "1234567"; // 아이디 값이 8자 이하인 경우
		try {
			test.setUserID(userID);
		} catch (IDFormatException e) {
			System.out.println(e.getMessage());
		}
	}
}

실행결과

아이디는 null일 수 없습니다.
아이디는 8자 이상 20자 이하로 쓰세요
```
- 여기서 발생하는 예외는 자바에서 제공하는 예외가 아니므로 예외 클래스를 직접 생성하여 예외를 발생시켜야 한다.
- 예외 메세지를 생성자에 넣어 예외클래스를 생성 후 throw 예약어로 직접 예외를 발생시킨다.